name: Monthly Report Cron

on:
  schedule:
   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  trigger-report:
    runs-on: ubuntu-latest
    steps:
      - name: Call Monthly Report API
        run: |
          curl --request GET \
               --url "https://timereport-backend.vercel.app/api/cron/monthly-report" \
               --max-time 900 \
               --fail-with-body
